Lvnod 47 home page
Lv-237-NodeJS/da-mi pull request #10
Opened 2017-05-26 11:26 UTC by AlbaMontis

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-46)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-47)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-48)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-51)

## Code reviewers

- [ ] @denisbodnar
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-05-26 12:44 UTC, denisbodnar submitted a review, later dismissed

2017-05-26 13:31 UTC, yuliannakorol submitted a review, later dismissed

2017-05-26 16:25 UTC, shyyka submitted a review, later dismissed

2017-05-26 21:35 UTC, 4asof4ik requested changes

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/components/CheckEmail/CheckEmail.js
> +export default class CheckEmail extends React.Component {
this component should be common for all messages

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/components/Home/Home.js
> +            <p className="center">OR</p>
bootstrap has own class text-center which align text

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/components/Home/Home.js
> +            <p id="homeText">Some text about our project!!!</p>
Why did you add id here?

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/components/Home/Home.scss
> +.center {
drop this style

2017-05-26 21:35 UTC, 4asof4ik commented on webpack/webpack.config.dev.js
> +      links: [
this is bad idea

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/components/Main/Main.js
>  export default class Main extends React.Component {
rename into Navigations or something else

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/router.js
> +import { About, Home, Contacts, Signup, Main, CheckEmail}
space before }

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/router.js
>    <Route path='/' component={Main}>
9 line has path "/" too

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/components/Signup/Signup.js
> +  render () {
read about react state

2017-05-26 21:35 UTC, 4asof4ik commented on app/src/components/Signup/Signup.js
> +          <Link to='/email'>
after click should redirect to login page and show message

2017-05-27 13:18 UTC, denisbodnar submitted a review, later dismissed

2017-05-31 07:20 UTC, 4asof4ik requested changes

2017-05-31 07:20 UTC, 4asof4ik commented on app/src/components/Login/Login.js
> +    this.handleChange = this.handleChange.bind(this);
create array for function and use .map

2017-05-31 07:20 UTC, 4asof4ik commented on app/src/components/Login/Login.js
> +                         value={this.state.email} onChange={this.handleChange}
onChange={value => this.handleValue('stateName', value)

2017-05-31 07:20 UTC, 4asof4ik commented on app/src/components/Login/Login.js
> +  handleChange(event) {
handleChange(state, event)

2017-05-31 11:31 UTC, yuliannakorol submitted a review, later dismissed

2017-05-31 11:41 UTC, denisbodnar submitted a review, later dismissed

2017-05-31 12:22 UTC, shyyka submitted a review, later dismissed

2017-05-31 19:13 UTC, 4asof4ik requested changes

2017-05-31 19:13 UTC, 4asof4ik commented on app/src/components/Login/Login.js
> +        <FormGroup controlId="email">
Create function which will be returning formgroup for email and password

2017-05-31 21:25 UTC, denisbodnar submitted a review, later dismissed

2017-05-31 21:42 UTC, shyyka submitted a review, later dismissed

2017-05-31 22:06 UTC, yuliannakorol submitted a review, later dismissed

2017-06-01 07:39 UTC, 4asof4ik requested changes

2017-06-01 07:39 UTC, 4asof4ik commented on app/src/components/Login/Login.js
> +      <Form horizontal onSubmit={this.handleSubmit}>
Form horizontal onSubmit={this.handleSubmit}
  {['email', password].map(param => {
      InputGroup id={param} type={param} .......
})}

2017-06-01 14:31 UTC, shyyka approved these changes

2017-06-01 16:01 UTC, denisbodnar approved these changes

2017-06-01 21:09 UTC, yuliannakorol approved these changes

2017-06-02 07:24 UTC, 4asof4ik approved these changes

2017-06-02 11:19 UTC, merged