Set sass lint rules
Lv-237-NodeJS/da-mi pull request #11
Opened 2017-05-27 10:14 UTC by yarvanya

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-28)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-53)

## Code reviewers

- [ ] @denisbodnar
- [ ] @AlbaMontis
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

I have set the sass lint for our project and added default rules.

## CHECK LIST

- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-05-27 11:06 UTC, denisbodnar submitted a review, later dismissed

2017-05-27 13:43 UTC, AlbaMontis submitted a review, later dismissed

2017-05-27 16:02 UTC, shyyka submitted a review, later dismissed

2017-05-28 12:22 UTC, 4asof4ik requested changes

2017-05-28 12:22 UTC, 4asof4ik commented on .travis.yml
> +  - sass-lint -v -q 'app/**/*.css'
we will have the only scss

2017-05-29 11:10 UTC, shyyka approved these changes

2017-05-29 11:24 UTC, AlbaMontis approved these changes

2017-05-29 11:36 UTC, denisbodnar approved these changes

2017-05-29 16:53 UTC, merged