LVNOD-54-Create-Redux-Setup
Lv-237-NodeJS/da-mi pull request #13
Opened 2017-06-01 21:08 UTC by denisbodnar

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-54)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-54)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @AlbaMontis
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-01 21:29 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-01 21:39 UTC, shyyka submitted a review, later dismissed

2017-06-01 22:47 UTC, AlbaMontis submitted a review, later dismissed

2017-06-02 08:53 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-02 09:14 UTC, shyyka submitted a review, later dismissed

2017-06-02 10:33 UTC, AlbaMontis commented on app/src/components/Test/Test.js
> +    this.onTitleChange = this.onTitleChange.bind(this);
With js6 arrow functions you don't need to bind

2017-06-02 10:33 UTC, AlbaMontis commented on app/src/components/Test/Test.js
> +  onTitleChange(event) {
onTitleChange = (event) => {...

2017-06-02 10:33 UTC, AlbaMontis commented on app/src/components/Test/Test.js
> +function mapStatetoProps(state, ownProps) {
Where do you use ownProps?

2017-06-02 11:48 UTC, denisbodnar commented on app/src/components/Test/Test.js
> +function mapStatetoProps(state, ownProps) {
ownProps represents any props passed to our component

https://stackoverflow.com/questions/41198842/what-is-the-use-of-the-ownprops-arg-in-mapstatetoprops-and-mapdispatchtoprops

2017-06-02 17:34 UTC, AlbaMontis submitted a review, later dismissed

2017-06-02 19:05 UTC, shyyka submitted a review, later dismissed

2017-06-02 19:14 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-05 09:22 UTC, 4asof4ik requested changes

2017-06-05 09:22 UTC, 4asof4ik commented on app/src/reducer/index.js
> +import { combineReducers } from 'redux';
Folder redux,  file name reducer

2017-06-05 09:22 UTC, 4asof4ik commented on app/src/reducer/itemReducer.js
> +export default function itemReducer(state = [], action) {
File name example: container "Test" => reducer test.js and import into reducer.js , rootReducer

2017-06-05 11:40 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-05 11:46 UTC, shyyka submitted a review, later dismissed

2017-06-05 18:34 UTC, 4asof4ik approved these changes

2017-06-05 19:01 UTC, AlbaMontis approved these changes

2017-06-05 19:02 UTC, merged