Lvnod 57 create registration component
Lv-237-NodeJS/da-mi pull request #14
Opened 2017-06-03 23:59 UTC by yurii-kokhalevych

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-57)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @AlbaMontis
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-06-04 07:12 UTC, avoytovich commented on app/src/containers/Signup/Signup.js
> +let request = require('superagent');
import request from 'superagent';

2017-06-04 07:13 UTC, yarvanya submitted a review, later dismissed

2017-06-04 07:23 UTC, avoytovich commented on app/src/containers/Signup/Signup.js
> +const FieldGroup = ({className, label, inErrors, ...props}) => {
Normally you would define a React component as a plain JavaScript class:
class Greeting extends React.Component {
  render() {
    return <h1>Hello, {this.props.name}</h1>;
  }
}

2017-06-04 07:27 UTC, avoytovich commented on app/src/containers/Signup/Signup.js
> +import React, { Component } from 'react';
why you use { Component } ???

2017-06-04 08:13 UTC, yurii-kokhalevych commented on app/src/containers/Signup/Signup.js
> +import React, { Component } from 'react';
export default class Signup extends Component

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +import { FormGroup, ControlLabel, FormControl, Button, ButtonToolbar, Form, HelpBlock } from 'react-bootstrap';
Do you use ButtonToolbar somewhere?

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +
Useless blank line.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +
Useless blank line.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +    .post('http://localhost:8081/api/reg/user')
It should not be hardcoded.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +          <FieldGroup
You missed 2 spaces here.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +          {['first_Name', 'last_Name'].map(param =>
Use 2 spaces for indentation.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.scss
> +
Useless blank line.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.scss
> +.LoginForm{
Missed space before {

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.scss
> +.containerLog{
Missed space before {

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +      <Form className='LoginForm' onSubmit={this.handleButtonClick}>
Fix indentation.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +     if (err || !res.ok) {
Fix indentation.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +validateField = (fieldName, value) => {
Missed space.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +let request = require('superagent');
Missed space before let.

2017-06-04 09:52 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.scss
> +	border: $bor-type $bor-width $bor-color;
Use 2 spaces.

2017-06-04 18:05 UTC, avoytovich commented on app/src/containers/Signup/Signup.js
> +import React, { Component } from 'react';
export default class Signup extends React.Component...чому не так?

2017-06-04 22:56 UTC, avoytovich commented on app/src/containers/Signup/Signup.js
> +      {inErrors && <HelpBlock>{inErrors}</HelpBlock>}
не можу зрозуміти, чому пишеш в JS як в JSX?

2017-06-05 07:00 UTC, yarvanya submitted a review, later dismissed

2017-06-05 08:16 UTC, AlbaMontis submitted a review, later dismissed

2017-06-05 08:43 UTC, avoytovich submitted a review, later dismissed

2017-06-08 19:49 UTC, 4asof4ik requested changes

2017-06-08 19:49 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +let user = {
hardcode ?

2017-06-08 19:49 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.scss
> +$bor-radius: 25px;
Create common styles for all and use them and here add component styles

2017-06-08 19:49 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +          'You have successfully signed up! For confirmation please visit your e-mail'
Add info messages file

2017-06-08 19:49 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +            'At least 6 characters, one (a-z), one (A-Z), one (0-9), one ($@$!%*?&)'
Messages file

2017-06-11 07:15 UTC, yarvanya commented on app/src/helper/constants.js
> +export default API;
Add an empty line...

2017-06-11 12:21 UTC, AlbaMontis commented on app/src/common.scss
> +$border-color-green: green;
Use hexadecimal colors or rgb.

2017-06-11 12:21 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +  return {
With arrow functions you can return object without word "return": => ({val: prop})

2017-06-11 12:21 UTC, AlbaMontis commented on app/src/redux/Signup.js
> +import { browserHistory } from 'react-router';
import { push } from 'react-router-redux';

2017-06-11 12:21 UTC, AlbaMontis commented on app/src/redux/Signup.js
> +          browserHistory.push('/'),
push('/');

2017-06-11 12:21 UTC, AlbaMontis commented on app/src/redux/Signup.js
> +};
> Semicolons should be included at the end of function expressions, but not at the end of function declarations.
https://google.github.io/styleguide/javascriptguide.xml#Semicolons

2017-06-11 12:21 UTC, AlbaMontis commented on app/src/redux/Signup.js
> +};
Missed space.

2017-06-11 16:31 UTC, yurii-kokhalevych commented on app/src/redux/Signup.js
> +          browserHistory.push('/'),
this must be ' ,'  with ';' doesn't work

2017-06-11 16:31 UTC, yurii-kokhalevych commented on app/src/redux/Signup.js
> +import { browserHistory } from 'react-router';
it is not necessary

2017-06-11 17:21 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +  errorClass = (error) => {
Useless ()

2017-06-11 17:21 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +    return (error.length === 0 ? '' : 'has-error');
You can write this arrow function without 'return'.

2017-06-11 17:21 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +const mapDispatchToProps = (dispatch) => ({
Useless ().

2017-06-11 17:21 UTC, AlbaMontis commented on app/src/redux/Signup.js
> +          browserHistory.push('/'),
I didn't mean ; , I meant react-router-redux method 'push'.

2017-06-12 04:55 UTC, AlbaMontis commented on app/src/common.scss
> +$border-color-white: #FFFFFF;
Why not just white?

2017-06-12 04:55 UTC, AlbaMontis commented on app/src/common.scss
> +$text-color-black: #000000;
What if I need black somewhere else, not for text?

2017-06-12 06:49 UTC, yarvanya submitted a review, later dismissed

2017-06-12 06:51 UTC, avoytovich submitted a review, later dismissed

2017-06-13 08:17 UTC, AlbaMontis commented on app/src/redux/Signup.js
> +return dispatch => {
Missed space before return.

2017-06-13 19:54 UTC, yarvanya submitted a review, later dismissed

2017-06-13 21:52 UTC, AlbaMontis submitted a review, later dismissed

2017-06-13 23:50 UTC, avoytovich submitted a review, later dismissed

2017-06-14 22:48 UTC, yarvanya submitted a review, later dismissed

2017-06-15 00:24 UTC, AlbaMontis submitted a review, later dismissed

2017-06-15 19:38 UTC, AlbaMontis submitted a review, later dismissed

2017-06-15 19:51 UTC, yarvanya submitted a review, later dismissed

2017-06-15 19:56 UTC, yarvanya submitted a review, later dismissed

2017-06-15 19:59 UTC, avoytovich submitted a review, later dismissed

2017-06-15 20:01 UTC, AlbaMontis submitted a review, later dismissed

2017-06-15 20:07 UTC, AlbaMontis submitted a review, later dismissed

2017-06-15 20:08 UTC, yarvanya submitted a review, later dismissed

2017-06-15 20:10 UTC, avoytovich submitted a review, later dismissed

2017-06-15 20:55 UTC, 4asof4ik requested changes

2017-06-15 20:55 UTC, 4asof4ik commented on app/src/common.scss
> +$margin: auto;
drop

2017-06-15 20:55 UTC, 4asof4ik commented on app/src/redux/reducer.js
> +import { routerReducer } from 'react-router-redux';
first should be vendor after that your

2017-06-15 20:55 UTC, 4asof4ik commented on app/src/helper/messages.js
> +  signup: 'You have successfully signed up! For confirmation please visit your e-mail',
successSignup

2017-06-15 20:55 UTC, 4asof4ik commented on app/src/helper/messages.js
> +  error: 'That email address is already in use',
emailExistError

2017-06-15 20:55 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +        <Form className='Signup' onSubmit={this.handleButtonClick}>
maybe use redux-form? https://redux-form.com/6.8.0/

2017-06-16 12:24 UTC, yurii-kokhalevych commented on app/src/containers/Signup/Signup.js
> +        <Form className='Signup' onSubmit={this.handleButtonClick}>
We thought about redux-form earlier but decided use react-bootstrap

2017-06-16 13:33 UTC, avoytovich submitted a review, later dismissed

2017-06-16 15:18 UTC, yarvanya submitted a review, later dismissed

2017-06-16 15:41 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +import request from 'superagent';
Do you need it here?

2017-06-16 15:41 UTC, AlbaMontis commented on app/src/containers/Signup/Signup.js
> +import { browserHistory } from 'react-router';
Do you use it here?

2017-06-16 16:25 UTC, AlbaMontis submitted a review, later dismissed

2017-06-16 16:31 UTC, avoytovich submitted a review, later dismissed

2017-06-16 16:42 UTC, yarvanya submitted a review, later dismissed

2017-06-16 21:28 UTC, 4asof4ik requested changes

2017-06-16 21:28 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +    let isErrors = this.state.isErrors;
let {isErrors, emailValid.............} = this.state;
check this

2017-06-16 21:28 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +          (this.state.confirmation === this.state.password) ? '' : `${messages.confirmationError}`;
read how separate ternary operator

2017-06-16 21:31 UTC, 4asof4ik requested changes

2017-06-16 21:31 UTC, 4asof4ik commented on app/src/redux/Signup.js
> +              dispatch(messageModal(messages.emailExistError)),
check spaces in this file

2017-06-16 21:40 UTC, 4asof4ik requested changes

2017-06-16 21:40 UTC, 4asof4ik commented on app/src/redux/Signup.js
> +        if (err || !res.ok) {
err || !res.ok && err.status == 422

2017-06-16 21:43 UTC, yurii-kokhalevych commented on app/src/redux/Signup.js
> +              dispatch(messageModal(messages.emailExistError)),
this structure of spaces want travis

2017-06-18 19:22 UTC, yarvanya submitted a review, later dismissed

2017-06-18 19:27 UTC, avoytovich submitted a review, later dismissed

2017-06-18 23:32 UTC, AlbaMontis commented on app/src/redux/Signup.js
> +import { push } from 'react-router-redux';
Do you use it in this file?

2017-06-19 06:43 UTC, avoytovich submitted a review, later dismissed

2017-06-19 07:24 UTC, yarvanya submitted a review, later dismissed

2017-06-19 07:25 UTC, AlbaMontis submitted a review, later dismissed

2017-06-19 10:17 UTC, avoytovich submitted a review, later dismissed

2017-06-19 13:21 UTC, avoytovich submitted a review, later dismissed

2017-06-19 13:37 UTC, yarvanya submitted a review, later dismissed

2017-06-19 14:33 UTC, AlbaMontis submitted a review, later dismissed

2017-06-19 21:36 UTC, 4asof4ik requested changes

2017-06-19 21:36 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +import style from './Signup.scss';
import './Signup.scss';

2017-06-19 21:36 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +    switch (fieldName) {
need rewrite

2017-06-20 09:56 UTC, yarvanya submitted a review, later dismissed

2017-06-20 09:57 UTC, avoytovich submitted a review, later dismissed

2017-06-20 10:20 UTC, AlbaMontis submitted a review, later dismissed

2017-06-21 22:58 UTC, 4asof4ik requested changes

2017-06-21 22:58 UTC, 4asof4ik commented on app/src/redux/Signup.js
> +      .post(API.HOST + API.PORT + '/api/auth/users')
/api/auth/users this is not auth /api/users (fix in beck-end too)

2017-06-21 22:58 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +      for(let key in errors) {
use map

2017-06-21 22:58 UTC, 4asof4ik commented on app/src/containers/Signup/Signup.js
> +          {['email', 'password', 'confirmation'].map(param =>
use the associative array with Object.keys

2017-06-21 23:04 UTC, yurii-kokhalevych commented on app/src/redux/Signup.js
> +      .post(API.HOST + API.PORT + '/api/auth/users')
if I will not used auth I get error { success: false, message: 'No token provided.'}

2017-06-22 19:37 UTC, yarvanya submitted a review, later dismissed

2017-06-22 20:19 UTC, AlbaMontis submitted a review, later dismissed

2017-06-22 20:57 UTC, 4asof4ik requested changes

2017-06-22 20:57 UTC, 4asof4ik commented on app/src/redux/reducer.js
> +import items from './Test';
drop  test component and other (redux route .....)

2017-06-22 21:01 UTC, avoytovich submitted a review, later dismissed

2017-06-22 21:30 UTC, yarvanya submitted a review, later dismissed

2017-06-22 21:31 UTC, avoytovich submitted a review, later dismissed

2017-06-23 05:13 UTC, AlbaMontis submitted a review, later dismissed

2017-06-23 16:41 UTC, omaik commented on .babelrc
> +  presets:["es2015", "stage-0", "react"]
minor, whitespace after a colon.

2017-06-23 18:59 UTC, yarvanya approved these changes

2017-06-23 19:22 UTC, avoytovich approved these changes

2017-06-23 20:31 UTC, AlbaMontis approved these changes

2017-06-23 20:32 UTC, 4asof4ik approved these changes

2017-06-23 22:05 UTC, merged