Lvnod 46 User autorization
Lv-237-NodeJS/da-mi pull request #15
Opened 2017-06-04 14:51 UTC by AlbaMontis

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-46)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-48)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @denisbodnar
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-04 16:22 UTC, denisbodnar approved these changes

2017-06-04 16:27 UTC, yurii-kokhalevych approved these changes

2017-06-04 19:37 UTC, shyyka approved these changes

2017-06-05 09:09 UTC, 4asof4ik requested changes

2017-06-05 09:09 UTC, 4asof4ik commented on app/src/helper/constants.js
> +  LOGIN: 'http://localhost:8082/api/auth/login'
Host and port

2017-06-05 09:09 UTC, 4asof4ik commented on app/src/components/Login/Login.js
> +    request
This should  be in action folder auth.action.js

2017-06-05 09:09 UTC, 4asof4ik commented on app/src/components/Navigation/Navigation.js
> +          {this.state.loggedIn &&
Logout should be in dropdown with edit profile

2017-06-05 09:09 UTC, 4asof4ik commented on app/src/components/Secret/Secret.js
> +export default class Secret extends React.Component {
Why you create this comp...

2017-06-05 12:03 UTC, 4asof4ik requested changes

2017-06-05 12:03 UTC, 4asof4ik commented on app/src/components/Navigation/Navigation.js
> +    window.location.reload();
redirect to root path

2017-06-07 17:17 UTC, closed without merging