Lvnod 70 create modal messenger
Lv-237-NodeJS/da-mi pull request #19
Opened 2017-06-04 23:11 UTC by yurii-kokhalevych

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-70)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @denisbodnar
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-06-05 09:31 UTC, 4asof4ik requested changes

2017-06-05 09:31 UTC, 4asof4ik commented on app/src/containers/Home/Home.js
> +            <PageHeader className="text-center">Da-Mi</PageHeader>
??

2017-06-05 09:31 UTC, 4asof4ik commented on app/src/containers/Message/Message.js
> +  showModal = (e) => {
Check other pr and write single handler

2017-06-05 09:31 UTC, 4asof4ik commented on app/src/containers/Message/Message.js
> +  SIGNUP: 'You have successfully signed up! For confirmation please visit your e-mail'
Create messages file for all messages ask guys

2017-06-05 12:00 UTC, 4asof4ik requested changes

2017-06-05 12:00 UTC, 4asof4ik commented on app/src/containers/Message/Message.scss
> +$bor-type: solid;
create file common  styles and import into your styles

2017-06-05 13:55 UTC, denisbodnar submitted a review, later dismissed

2017-06-05 14:14 UTC, shyyka submitted a review, later dismissed

2017-06-05 15:13 UTC, yuliannakorol submitted a review, later dismissed

2017-06-05 22:41 UTC, shyyka submitted a review, later dismissed

2017-06-05 23:21 UTC, yuliannakorol submitted a review, later dismissed

2017-06-08 19:34 UTC, 4asof4ik requested changes

2017-06-08 19:34 UTC, 4asof4ik commented on app/src/containers/Message/Message.js
> +  showModal = () => {
Where you use this ?

2017-06-10 05:28 UTC, 4asof4ik requested changes

2017-06-10 05:28 UTC, 4asof4ik commented on app/src/containers/Message/Message.js
> +            <p>{messages.signup}</p>
Need dynamic changing messages

2017-06-10 22:16 UTC, shyyka submitted a review, later dismissed

2017-06-11 08:35 UTC, shyyka submitted a review, later dismissed

2017-06-11 10:00 UTC, denisbodnar submitted a review, later dismissed

2017-06-11 10:00 UTC, denisbodnar commented on app/src/components/Message/Message.js
> +  hide = () =>{
whitespace before {

2017-06-11 16:59 UTC, denisbodnar submitted a review, later dismissed

2017-06-11 17:10 UTC, yuliannakorol submitted a review, later dismissed

2017-06-11 18:26 UTC, shyyka submitted a review, later dismissed

2017-06-12 21:52 UTC, 4asof4ik requested changes

2017-06-12 21:52 UTC, 4asof4ik commented on app/src/common.scss
> +$border-type-solid: solid;
example:
$border-bold: 10px solid $red;

2017-06-12 23:12 UTC, shyyka submitted a review, later dismissed

2017-06-13 06:17 UTC, denisbodnar submitted a review, later dismissed

2017-06-13 12:21 UTC, shyyka submitted a review, later dismissed

2017-06-13 19:58 UTC, yuliannakorol submitted a review, later dismissed

2017-06-13 20:21 UTC, 4asof4ik requested changes

2017-06-13 20:21 UTC, 4asof4ik commented on app/src/components/Message/Message.js
> +      >
?

2017-06-13 20:24 UTC, 4asof4ik requested changes

2017-06-13 20:24 UTC, 4asof4ik commented on app/src/common.scss
> +$borderRadiusBase: 5px;
Please create normal var for border

2017-06-15 06:11 UTC, 4asof4ik requested changes

2017-06-15 06:11 UTC, 4asof4ik commented on app/src/common.scss
> +$border1: 2px solid $white;
border-white maybe?

2017-06-15 06:11 UTC, 4asof4ik commented on app/src/components/Message/Message.scss
> +$position: absolute;
drop this

2017-06-15 06:11 UTC, 4asof4ik commented on app/src/components/Message/Message.scss
> +$left: 30%;
% bad think

2017-06-15 06:11 UTC, 4asof4ik commented on app/src/components/Message/Message.scss
> +$width: 400px;
drop all your var

2017-06-15 18:43 UTC, denisbodnar submitted a review, later dismissed

2017-06-15 19:25 UTC, yuliannakorol submitted a review, later dismissed

2017-06-15 19:37 UTC, shyyka submitted a review, later dismissed

2017-06-15 20:32 UTC, 4asof4ik requested changes

2017-06-15 20:32 UTC, 4asof4ik commented on app/src/components/Message/Message.js
> +const mapStatetoProps = (state, ownProps) => ({
where you use ownProps

2017-06-15 20:32 UTC, 4asof4ik commented on app/src/common.scss
> +$margin: auto;
drop

2017-06-16 13:16 UTC, denisbodnar submitted a review, later dismissed

2017-06-16 13:41 UTC, shyyka submitted a review, later dismissed

2017-06-16 14:56 UTC, yuliannakorol submitted a review, later dismissed

2017-06-16 20:57 UTC, shyyka submitted a review, later dismissed

2017-06-16 21:01 UTC, denisbodnar submitted a review, later dismissed

2017-06-17 10:02 UTC, yuliannakorol submitted a review, later dismissed

2017-06-18 10:00 UTC, denisbodnar approved these changes

2017-06-18 10:09 UTC, yuliannakorol approved these changes

2017-06-18 10:26 UTC, shyyka approved these changes

2017-06-18 19:26 UTC, 4asof4ik approved these changes

2017-06-18 19:34 UTC, merged