Lvnod 47 auth
Lv-237-NodeJS/da-mi pull request #21
Opened 2017-06-07 15:27 UTC by AlbaMontis

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-46)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-76)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-48)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @denisbodnar
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-07 18:02 UTC, denisbodnar submitted a review, later dismissed

2017-06-07 18:02 UTC, denisbodnar commented on app/src/helper/constants.js
> +export { API };
export API;

2017-06-07 18:04 UTC, AlbaMontis commented on app/src/redux/Login.js
> +export function logout(dispatch) {
Delete dispatch

2017-06-07 18:04 UTC, AlbaMontis commented on app/src/store/configureStore.js
> +import { routerMiddleware, push } from 'react-router-redux';
Delete push

2017-06-07 18:20 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-07 18:40 UTC, shyyka submitted a review, later dismissed

2017-06-07 19:07 UTC, shyyka submitted a review, later dismissed

2017-06-07 19:57 UTC, denisbodnar submitted a review, later dismissed

2017-06-07 20:51 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-08 06:18 UTC, AlbaMontis commented on app/src/helper/constants.js
> +export { API };
It could be `export const API`, but not `export API`

2017-06-08 07:40 UTC, denisbodnar submitted a review, later dismissed

2017-06-08 07:40 UTC, denisbodnar commented on app/src/redux/reducer.js
> +import login from './Login'
;

2017-06-08 08:28 UTC, denisbodnar submitted a review, later dismissed

2017-06-08 10:56 UTC, shyyka submitted a review, later dismissed

2017-06-08 13:42 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-08 19:31 UTC, 4asof4ik requested changes

2017-06-08 19:31 UTC, 4asof4ik commented on app/src/redux/Login.js
> +      return Object.assign({}, {
You can return without object.assign

2017-06-08 19:31 UTC, 4asof4ik commented on app/src/redux/Login.js
> +      .send({email: email, password: password})
Create let user with params

2017-06-08 19:31 UTC, 4asof4ik commented on app/src/redux/Login.js
> +    isToken = false;
Read how separate  this operator

2017-06-08 19:31 UTC, 4asof4ik commented on app/src/components/Secret/Secret.js
> +import React from 'react';
Why you add this component

2017-06-09 04:29 UTC, AlbaMontis commented on app/src/components/Secret/Secret.js
> +import React from 'react';
I need some component to mount, then token comes. Yulianna will put her component here later.

2017-06-09 06:59 UTC, AlbaMontis commented on app/src/redux/Login.js
> +      return Object.assign({}, {
Done.

2017-06-09 06:59 UTC, AlbaMontis commented on app/src/redux/Login.js
> +    isToken = false;
Done.

2017-06-09 06:59 UTC, AlbaMontis commented on app/src/redux/Login.js
> +      .send({email: email, password: password})
Done.

2017-06-09 08:00 UTC, denisbodnar submitted a review, later dismissed

2017-06-09 11:48 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-09 14:47 UTC, shyyka submitted a review, later dismissed

2017-06-10 05:22 UTC, 4asof4ik requested changes

2017-06-10 05:22 UTC, 4asof4ik commented on app/src/redux/Login.js
> +  }
;

2017-06-10 05:22 UTC, 4asof4ik commented on app/src/containers/Home/Home.js
> +        {!this.props.isToken ?
Should be IsAuth  and redirect to default page when user is auth

2017-06-12 20:50 UTC, yurii-kokhalevych approved these changes

2017-06-12 21:03 UTC, denisbodnar approved these changes

2017-06-12 21:31 UTC, shyyka approved these changes

2017-06-12 22:26 UTC, 4asof4ik approved these changes

2017-06-12 22:36 UTC, merged