Lvnod 72 create eventDetails component
Lv-237-NodeJS/da-mi pull request #22
Opened 2017-06-11 22:50 UTC by shyyka

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @AlbaMontis
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-12 11:09 UTC, avoytovich commented on app/src/containers/Event/EventDetails.js
> +        return item;
you will be right at all if do it throw findIndex...

2017-06-12 11:18 UTC, yarvanya commented on app/src/redux/eventReducers.js
> +const apiUrl = 'http://localhost:8082';
Delete this apiUrl, we will have this const in helper folder.

2017-06-12 11:18 UTC, yarvanya commented on app/src/redux/eventReducers.js
> +    .get(apiUrl + '/api/events')
Use ".get(API.HOST + API.PORT + '/api/events')".

2017-06-12 11:53 UTC, AlbaMontis commented on app/src/containers/Event/EventDetails.js
> +    const event = this.state.events.filter((item) => {
You can omit () around item.

2017-06-12 11:53 UTC, AlbaMontis commented on app/src/containers/Event/EventDetails.js
> +const mapStateToProps = (state, ownProps) => {
You can return object without "return", just `....=> ({prop: val})`

2017-06-12 11:53 UTC, AlbaMontis commented on app/src/containers/Event/EventDetails.js
> +  return {
The same as above. And useless ().

2017-06-12 11:53 UTC, AlbaMontis commented on app/src/redux/eventReducers.js
> +  return state;
Default

2017-06-12 15:13 UTC, shyyka commented on app/src/redux/eventReducers.js
> +    .get(apiUrl + '/api/events')
Done.

2017-06-12 15:13 UTC, shyyka commented on app/src/redux/eventReducers.js
> +const apiUrl = 'http://localhost:8082';
Done.

2017-06-12 16:40 UTC, shyyka commented on app/src/containers/Event/EventDetails.js
> +  return {
Done.

2017-06-12 16:40 UTC, shyyka commented on app/src/redux/eventReducers.js
> +  return state;
Done.

2017-06-12 16:51 UTC, shyyka commented on app/src/containers/Event/EventDetails.js
> +        return item;
As for me it looks more simple and elegant)

2017-06-12 18:32 UTC, yarvanya submitted a review, later dismissed

2017-06-12 20:33 UTC, shyyka commented on app/src/containers/Event/EventDetails.js
> +const mapStateToProps = (state, ownProps) => {
Done.

2017-06-12 20:33 UTC, shyyka commented on app/src/containers/Event/EventDetails.js
> +    const event = this.state.events.filter((item) => {
Done.

2017-06-12 21:03 UTC, avoytovich submitted a review, later dismissed

2017-06-12 21:38 UTC, AlbaMontis submitted a review, later dismissed

2017-06-12 22:34 UTC, 4asof4ik requested changes

2017-06-12 22:34 UTC, 4asof4ik commented on app/src/redux/reducer.js
> +  events: eventReducers,
check how include in other PR

2017-06-12 22:34 UTC, 4asof4ik commented on app/src/redux/eventReducers.js
> +  state = {
create let and include here

2017-06-12 22:34 UTC, 4asof4ik commented on app/src/redux/eventReducers.js
> +            };
check space in all PR

2017-06-12 22:34 UTC, 4asof4ik commented on app/src/containers/Event/EventDetails.js
> +      events: [],
this is event detail but not events

check all file

2017-06-13 02:41 UTC, shyyka commented on app/src/redux/eventReducers.js
> +  state = {
Done.

2017-06-13 02:41 UTC, shyyka commented on app/src/redux/reducer.js
> +  events: eventReducers,
Done.

2017-06-13 02:41 UTC, shyyka commented on app/src/redux/eventReducers.js
> +            };
Done.

2017-06-13 08:30 UTC, AlbaMontis commented on app/src/containers/Gift/sampleGift.js
> +import { PageHeader, } from 'react-bootstrap';
Useless ,

2017-06-13 08:30 UTC, AlbaMontis commented on app/src/containers/Gift/sampleGift.js
> +          <div className="list-group">
Fix indentation.

2017-06-13 08:30 UTC, AlbaMontis commented on app/src/containers/Guest/sampleGuest.js
> +import { PageHeader, } from 'react-bootstrap';
Useless ,

2017-06-13 08:30 UTC, AlbaMontis commented on app/src/containers/Guest/sampleGuest.js
> +          <div className="list-group">
Fix indentation.

2017-06-13 08:30 UTC, AlbaMontis commented on app/src/redux/eventReducers.js
> +  return (dispatch) => {
useless ().

2017-06-13 08:30 UTC, AlbaMontis commented on app/src/redux/eventReducers.js
> +import request from 'superagent';
Import from './../helper/request'

2017-06-13 14:27 UTC, shyyka commented on app/src/containers/Gift/sampleGift.js
> +          <div className="list-group">
Done.

2017-06-13 14:27 UTC, shyyka commented on app/src/containers/Gift/sampleGift.js
> +import { PageHeader, } from 'react-bootstrap';
Done.

2017-06-13 14:27 UTC, shyyka commented on app/src/containers/Guest/sampleGuest.js
> +import { PageHeader, } from 'react-bootstrap';
Done.

2017-06-13 14:27 UTC, shyyka commented on app/src/containers/Guest/sampleGuest.js
> +          <div className="list-group">
Done.

2017-06-13 14:34 UTC, shyyka commented on app/src/redux/eventReducers.js
> +  return (dispatch) => {
Done.

2017-06-13 14:34 UTC, shyyka commented on app/src/redux/eventReducers.js
> +import request from 'superagent';
Done.

2017-06-13 16:14 UTC, AlbaMontis submitted a review, later dismissed

2017-06-13 17:35 UTC, yarvanya submitted a review, later dismissed

2017-06-13 18:08 UTC, AlbaMontis submitted a review, later dismissed

2017-06-13 21:09 UTC, avoytovich submitted a review, later dismissed

2017-06-13 21:19 UTC, shyyka commented on app/src/containers/Event/EventDetails.js
> +      events: [],
Done.

2017-06-15 01:14 UTC, AlbaMontis commented on app/src/containers/Event/EventDetails.js
> +  constructor (props, context) {
It looks like you don't need constructor here.

2017-06-15 01:14 UTC, AlbaMontis commented on app/src/redux/reducer.js
> +export default combineReducers({
Delete spaces at the end.

2017-06-15 01:14 UTC, AlbaMontis commented on package.json
> +    "babel-plugin-transform-decorators-legacy": "^1.3.4",
I think it should be in "dependencies".

2017-06-15 01:36 UTC, shyyka commented on package.json
> +    "babel-plugin-transform-decorators-legacy": "^1.3.4",
They recommend in dev - https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy

2017-06-15 01:55 UTC, shyyka commented on app/src/containers/Event/EventDetails.js
> +  constructor (props, context) {
Yes.

2017-06-15 02:22 UTC, shyyka commented on app/src/redux/reducer.js
> +export default combineReducers({
Done.

2017-06-15 05:46 UTC, AlbaMontis submitted a review, later dismissed

2017-06-15 08:19 UTC, avoytovich submitted a review, later dismissed

2017-06-15 12:18 UTC, yarvanya submitted a review, later dismissed

2017-06-15 17:01 UTC, yarvanya submitted a review, later dismissed

2017-06-15 19:41 UTC, AlbaMontis submitted a review, later dismissed

2017-06-15 19:41 UTC, AlbaMontis commented on .babelrc
> +  presets:["es2015", "stage-0", "react"],
Useless ,

2017-06-15 20:11 UTC, shyyka commented on .babelrc
> +  presets:["es2015", "stage-0", "react"],
Trailing commas makes version-control diffs cleaner, you can simply add a new line without modifying the previously last line ...

2017-06-15 20:17 UTC, avoytovich submitted a review, later dismissed

2017-06-15 21:03 UTC, 4asof4ik approved these changes

2017-06-15 21:03 UTC, 4asof4ik commented on app/src/containers/Event/EventDetails.js
> +const mapStateToProps = (state, ownProps) => ({
where you use ownProps

2017-06-15 22:28 UTC, avoytovich approved these changes

2017-06-16 04:30 UTC, AlbaMontis approved these changes

2017-06-16 06:05 UTC, yarvanya approved these changes

2017-06-16 10:16 UTC, merged