Lvnod-69 create dashboard component
Lv-237-NodeJS/da-mi pull request #24
Opened 2017-06-13 01:56 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-69)

## Code reviewers

- [ ] @AlbaMontis
- [ ] @shyyka
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of change

- added Dashboard component with tab sub-navigation
- added mock EventsList component that will be implemented in another task/pull request

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-13 05:40 UTC, shyyka submitted a review, later dismissed

2017-06-13 08:22 UTC, AlbaMontis commented on app/src/containers/Dashboard/Dashboard.js
> +    </Tab.Container>
Fix indentation.

2017-06-13 08:22 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +            <thead>
Use 2 spaces for indentation.

2017-06-13 16:08 UTC, AlbaMontis commented on app/src/containers/Dashboard/Dashboard.js
> +                <NavItem eventKey='first'>
You can do something like:
 `['My Cabinet', 'My events'...].map((title, index) => 
  <NavItem eventKey={index}>
                   {title}
 </NavItem>
)`

2017-06-13 16:08 UTC, AlbaMontis commented on app/src/containers/Dashboard/Dashboard.js
> +                <Tab.Pane eventKey='first'>
The same as above.

2017-06-14 07:44 UTC, avoytovich commented on app/src/containers/Events/EventsList.js
> +import { Link } from 'react-router';
why did you import this module?

2017-06-14 11:11 UTC, AlbaMontis submitted a review, later dismissed

2017-06-14 20:26 UTC, avoytovich submitted a review, later dismissed

2017-06-15 14:20 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +  return {
You can just '=>({prop: Val})' without return.

2017-06-15 14:20 UTC, AlbaMontis commented on app/src/redux/EventsReducers.js
> +  return (dispatch) => {
Useless ()

2017-06-15 15:43 UTC, shyyka submitted a review, later dismissed

2017-06-15 21:23 UTC, avoytovich submitted a review, later dismissed

2017-06-15 22:18 UTC, shyyka submitted a review, later dismissed

2017-06-16 04:32 UTC, AlbaMontis submitted a review, later dismissed

2017-06-16 07:14 UTC, 4asof4ik requested changes

2017-06-16 07:14 UTC, 4asof4ik commented on app/src/containers/Dashboard/Dashboard.js
> +                ].map((title, index) => <NavItem eventKey={index}> {title} </NavItem>)}
drop spaces {title}
check all PR

2017-06-16 07:14 UTC, 4asof4ik commented on app/src/containers/Events/EventsList.js
> +
drop

2017-06-16 07:14 UTC, 4asof4ik commented on app/src/containers/Events/EventsList.js
> +    const eventNode = this.props.events.events.map((item) => {
events.events what is that?

2017-06-16 07:14 UTC, 4asof4ik commented on app/src/containers/Events/EventsList.js
> +
drop empty lines and 51,55

2017-06-16 07:14 UTC, 4asof4ik commented on app/src/containers/Events/EventsList.js
> +  events: state.events,
drop , check all PR

2017-06-16 10:13 UTC, shyyka submitted a review, later dismissed

2017-06-16 10:27 UTC, AlbaMontis submitted a review, later dismissed

2017-06-16 11:34 UTC, shyyka submitted a review, later dismissed

2017-06-16 11:35 UTC, avoytovich submitted a review, later dismissed

2017-06-16 13:02 UTC, avoytovich submitted a review, later dismissed

2017-06-16 15:34 UTC, AlbaMontis approved these changes

2017-06-16 15:34 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +    const data = this.props.eventsList;
Useless const.

2017-06-16 15:34 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +  eventsList: state.eventsList
state.eventsList.events

2017-06-16 15:34 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +const mapStateToProps = (state) => ({
Useless ();

2017-06-16 15:34 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +const mapDispatchToProps = (dispatch) => ({
Useless ();

2017-06-16 15:44 UTC, shyyka submitted a review, later dismissed

2017-06-16 20:08 UTC, AlbaMontis submitted a review, later dismissed

2017-06-17 18:41 UTC, avoytovich submitted a review, later dismissed

2017-06-17 19:20 UTC, 4asof4ik requested changes
Dashboard should be in components folder

2017-06-17 19:20 UTC, 4asof4ik commented on app/src/redux/EventsReducers.js
> +            payload: err,});
new line })

2017-06-19 19:31 UTC, closed without merging