LVNOD-109_set_eslint_on_Travis_on_front_end
Lv-237-NodeJS/da-mi pull request #25
Opened 2017-06-14 18:53 UTC by yarvanya

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-109)

## Code reviewers

- [ ] @denisbodnar
- [ ] @AlbaMontis
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

I've added eslint rules for Travis CI.

## CHECK LIST
- [ ]  СI passed
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-14 21:56 UTC, 4asof4ik requested changes

2017-06-14 21:56 UTC, 4asof4ik commented on .travis.yml
> +  - eslint ./app/src
Need add for test folder too.

2017-06-14 21:56 UTC, 4asof4ik commented on .eslintrc.json
> +    "rules": {
Empty line  in the end of file

2017-06-14 22:12 UTC, yarvanya commented on .eslintrc.json
> +    "rules": {
I have this rule.

2017-06-14 22:12 UTC, yarvanya commented on .travis.yml
> +  - eslint ./app/src
Done.

2017-06-14 22:22 UTC, AlbaMontis commented on .eslintrc.json
> +            "error", 2, { "SwitchCase": 1 }
Did you check indentation in this file? :)

2017-06-14 22:33 UTC, yarvanya commented on .eslintrc.json
> +            "error", 2, { "SwitchCase": 1 }
Yes, I did))

2017-06-15 00:28 UTC, AlbaMontis commented on .eslintrc.json
> +            "error", 2, { "SwitchCase": 1 }
So why do you use 4 spaces here? Is this file special?

2017-06-15 06:07 UTC, 4asof4ik approved these changes

2017-06-15 06:18 UTC, merged