Lvnod-69 create dashboard component and events list
Lv-237-NodeJS/da-mi pull request #28
Opened 2017-06-19 00:07 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-69)

## Code reviewers

- [ ] @AlbaMontis
- [ ] @shyyka
- [] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of change

- added Dashboard component
- added EventsList  container
- created events list reducers

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-19 07:21 UTC, AlbaMontis commented on app/src/components/Dashboard/Dashboard.js
> +import EventsList from '../../containers/Events/EventsList';
import { EventList } from '../../containers'.

2017-06-19 07:21 UTC, AlbaMontis commented on app/src/components/Dashboard/dashboard.scss
> +    position: relative; left: 15px; top: 15;
2 spaces for indentation. Every style rule in new line.

2017-06-19 07:21 UTC, AlbaMontis commented on app/src/containers/Events/eventsList.scss
> +    display: inline-block;
Fix indentation.

2017-06-19 07:21 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +import { ListGroup,ListGroupItem} from 'react-bootstrap';
Missed space after ListGroup, .

2017-06-19 07:21 UTC, AlbaMontis commented on app/src/components/Dashboard/Dashboard.js
> +import { Nav, NavItem, Tab, Row, Col } from 'react-bootstrap';
I can't find where do you use Tab and Row in this file.

2017-06-19 09:28 UTC, shyyka submitted a review, later dismissed

2017-06-19 15:30 UTC, AlbaMontis commented on app/src/components/Dashboard/Dashboard.js
> +import style from './dashboard.scss';
You can write just 'import from './dashboard.scss';'

2017-06-19 15:30 UTC, AlbaMontis commented on app/src/containers/Main/Main.js
> +import * as loginActions from '../../redux/Login';
You don't use actions in this file.

2017-06-19 15:30 UTC, AlbaMontis commented on app/src/containers/Main/Main.js
> +const mapDispatchToProps = dispatch => ({
You don't use actions in this file.

2017-06-19 15:30 UTC, AlbaMontis commented on app/src/redux/EventsReducers.js
> +        error: action.payload
Can't find where do you use this state.

2017-06-19 17:34 UTC, shyyka submitted a review, later dismissed

2017-06-19 20:30 UTC, avoytovich submitted a review, later dismissed

2017-06-19 21:07 UTC, 4asof4ik requested changes

2017-06-19 21:07 UTC, 4asof4ik commented on app/src/containers/Home/Home.js
> -        <Message />
why you drop Message

2017-06-20 07:55 UTC, shyyka submitted a review, later dismissed

2017-06-20 08:13 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +    this.setState({ eventsList: this.props.eventsList });
Delete this.

2017-06-20 08:13 UTC, AlbaMontis commented on app/src/containers/Events/EventsList.js
> +    const eventNode = this.props.eventsList.map((item) => {
Useless () around item.

2017-06-20 08:54 UTC, shyyka submitted a review, later dismissed

2017-06-20 09:40 UTC, AlbaMontis submitted a review, later dismissed

2017-06-20 10:04 UTC, shyyka submitted a review, later dismissed

2017-06-20 10:18 UTC, avoytovich submitted a review, later dismissed

2017-06-21 22:55 UTC, 4asof4ik approved these changes

2017-06-21 22:58 UTC, denisbodnar approved these changes

2017-06-21 22:59 UTC, shyyka approved these changes

2017-06-21 22:59 UTC, merged