Lvnod-74-Profile dropdown
Lv-237-NodeJS/da-mi pull request #29
Opened 2017-06-19 19:34 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-74

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @denisbodnar

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of change
- Created Profile drop-down component for navigation bar
- Created Profile reducers
- Created test Profile container (will be developed in another task and PR)

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-19 21:00 UTC, 4asof4ik requested changes

2017-06-19 21:00 UTC, 4asof4ik commented on app/src/components/Navigation/Navigation.js
> +import {ProfileDropDown} from './../';
spaces after and before {}

2017-06-19 21:00 UTC, 4asof4ik commented on app/src/components/ProfileDropDown/ProfileDropDown.js
> +
here add constructor with state profile

2017-06-19 21:00 UTC, 4asof4ik commented on app/src/components/ProfileDropDown/ProfileDropDown.js
> +        <NavDropdown style={{display: 'inline-block'}} eventKey={5} id='basic-nav-dropdown'
style={{display: 'inline-block'}} what 0_o

2017-06-19 22:44 UTC, yarvanya submitted a review, later dismissed

2017-06-26 07:17 UTC, yarvanya submitted a review, later dismissed

2017-06-26 07:20 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-26 07:56 UTC, denisbodnar submitted a review, later dismissed

2017-06-26 12:15 UTC, 4asof4ik requested changes

2017-06-26 12:15 UTC, 4asof4ik commented on app/src/redux/reducer.js
> +import profile from './ProfileReducers';
rename all reducer file with camelCase

2017-06-26 12:15 UTC, 4asof4ik commented on app/src/components/ProfileDropDown/ProfileDropDown.js
> +    this.props.actions.loginActions.checkToken();
why check token here?

2017-06-26 12:15 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +  profile: state.profile.profile,
profile.profile ?

2017-06-26 12:15 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +  userId: state.login.userId
you have userId in sesion storage

2017-06-26 12:15 UTC, 4asof4ik commented on app/src/redux/ProfileReducers.js
> +            payload: err
error

2017-06-26 14:32 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-26 14:32 UTC, yarvanya submitted a review, later dismissed

2017-06-26 15:43 UTC, 4asof4ik requested changes

2017-06-26 15:43 UTC, 4asof4ik commented on app/src/components/ProfileDropDown/ProfileDropDown.js
> +import { Link } from 'react-router';
where you use this?

2017-06-26 15:43 UTC, 4asof4ik commented on app/src/components/ProfileDropDown/ProfileDropDown.js
> +    const profile = this.props.profile;
{ profile, action } = this.props

2017-06-26 15:43 UTC, 4asof4ik commented on app/src/components/ProfileDropDown/ProfileDropDown.js
> +          <MenuItem eventKey={5.2} onClick={this.props.actions.loginActions.logout}>Log Out</MenuItem>
actions.loginActions.logout

2017-06-26 15:43 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +    const profile = this.props.profile;
look above

2017-06-26 19:10 UTC, 4asof4ik approved these changes

2017-06-26 19:18 UTC, yarvanya approved these changes

2017-06-26 19:21 UTC, merged