Lvnod 77 create newevent component
Lv-237-NodeJS/da-mi pull request #32
Opened 2017-06-24 18:34 UTC by yarvanya

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-77)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-106)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-107)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-108)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @denisbodnar
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

- First, I have created Newevent container component.
- Second, I've added route for this.
- Third, I have created the createNewEventReducer with all needed actions for the Newevent container component.
- Fourth, I've added my child createNewEventReducer for the main reducer.

## CHECK LIST
- [ ]  СI passed
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-24 20:34 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-24 21:09 UTC, denisbodnar submitted a review, later dismissed

2017-06-26 06:55 UTC, 4asof4ik requested changes

2017-06-26 06:55 UTC, 4asof4ik commented on app/src/router.js
> +    <Route  path='newevent' component={Newevent}/>
camelCase

2017-06-26 06:55 UTC, 4asof4ik commented on app/src/redux/reducer.js
> +import newevent from './createNewEventReducer';
without create and naming files shouldn't be different, fix this

2017-06-26 06:55 UTC, 4asof4ik commented on app/src/containers/Newevent/Newevent.js
> +      name: /^.{4,}$/,
drop this and check if event length more than 4

2017-06-26 06:55 UTC, 4asof4ik commented on app/src/containers/Newevent/Newevent.js
> +      date_event:  /^(0?[1-9]|[12][0-9]|3[01])[/](0?[1-9]|1[012])[/]\d{4}$/
drop and use datapicker

2017-06-26 06:55 UTC, 4asof4ik commented on app/src/containers/index.js
> +export Newevent from './Newevent/Newevent';
camelCase

2017-06-26 06:55 UTC, 4asof4ik commented on app/src/containers/Newevent/Newevent.js
> +      this.state.name,
why you send each state

2017-06-26 06:55 UTC, 4asof4ik commented on app/src/redux/createNewEventReducer.js
> +export function createNewEvent(name, date_event, location_name, longitude, latitude, description) {
O_o

2017-07-01 18:52 UTC, 4asof4ik requested changes

2017-07-01 18:52 UTC, 4asof4ik commented on app/src/router.js
> +  Gift, Guest, EventsList, EventDetails, Profile, newEvent } from './containers';
Guest?

2017-07-01 18:52 UTC, 4asof4ik commented on app/src/redux/newEventReducers.js
> +const CREATE_NEW_EVENT_SUCCESS = 'CREATE_NEW_EVENT_SUCCESS';
Empty line

2017-07-01 18:52 UTC, 4asof4ik commented on app/src/redux/newEventReducers.js
> +  };
Where error

2017-07-01 18:52 UTC, 4asof4ik commented on app/src/redux/newEventReducers.js
> +    type: CREATE_NEW_EVENT_SUCCESS
Where event

2017-07-01 18:52 UTC, 4asof4ik commented on app/src/redux/newEventReducers.js
> +  };
Where error

2017-07-02 17:32 UTC, denisbodnar submitted a review, later dismissed

2017-07-03 22:08 UTC, 4asof4ik requested changes

2017-07-03 22:08 UTC, 4asof4ik commented on app/src/redux/reducer.js
>  import invite from './invite';
rename inviteReducers

2017-07-03 22:08 UTC, 4asof4ik commented on app/src/containers/Newevent/Newevent.js
> +    this.setState({ [param]: value}, () => {this.getValidationState();});
drop space { [

2017-07-03 22:08 UTC, 4asof4ik commented on app/src/containers/Newevent/Newevent.js
> +              <FormGroup key={param}>
create const and use them 99 line too

2017-07-04 19:40 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-04 20:48 UTC, denisbodnar submitted a review, later dismissed

2017-07-04 21:27 UTC, yuliannakorol submitted a review, later dismissed

2017-07-05 07:58 UTC, 4asof4ik approved these changes

2017-07-05 07:58 UTC, 4asof4ik commented on app/src/containers/Newevent/Newevent.js
> +import DateTimeField from 'react-bootstrap-datetimepicker';
first  include all vendor after that own

2017-07-05 08:12 UTC, merged