Lvnod 123 create about us
Lv-237-NodeJS/da-mi pull request #33
Opened 2017-06-25 21:20 UTC by yurii-kokhalevych

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-123)

## Code reviewers

- [ ] @denisbodnar
- [ ] @AlbaMontis
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-06-25 21:39 UTC, AlbaMontis commented on package-lock.json
>        "integrity": "sha1-u8qATAQE2cZAECsrZWrkzVvqNcg="
Put this file to the gitignore.

2017-06-25 21:49 UTC, AlbaMontis commented on app/src/containers/About/About.js
> +              <Image src={Names[param]} thumbnail/>
It would be better to put images into backgrounds.

2017-06-26 07:52 UTC, denisbodnar submitted a review, later dismissed

2017-06-26 07:52 UTC, denisbodnar commented on app/src/containers/About/About.js
> +            Then it's up to you! Our project will help you to get only the desired
use &apos; instead of '

2017-06-26 08:40 UTC, shyyka submitted a review, later dismissed

2017-06-26 23:06 UTC, denisbodnar submitted a review, later dismissed

2017-06-27 09:22 UTC, AlbaMontis commented on app/src/containers/About/About.scss
> +  background-repeat: $background-repeat;
You can put it after url in background.

2017-06-27 09:22 UTC, AlbaMontis commented on package-lock.json
> +          "resolved": "https://registry.npmjs.org/acorn/-/acorn-4.0.13.tgz"
Please remove this file and put it into gitignore.

2017-06-27 09:37 UTC, AlbaMontis commented on app/src/containers/About/About.scss
> +#Maryana {
I think you can use sass map here or something like that.

2017-06-27 11:32 UTC, shyyka submitted a review, later dismissed

2017-06-27 14:09 UTC, denisbodnar submitted a review, later dismissed

2017-06-27 14:23 UTC, shyyka submitted a review, later dismissed

2017-06-27 16:26 UTC, AlbaMontis submitted a review, later dismissed

2017-06-28 08:56 UTC, 4asof4ik requested changes

2017-06-28 08:56 UTC, 4asof4ik commented on app/src/containers/About/About.scss
> +#photo-Maryana, #photo-Denis, #photo-Ivan,
use class team

2017-06-28 08:56 UTC, 4asof4ik commented on app/src/containers/About/About.js
> +              <div id={names[param]} className="container"></div>
use common class for all img

2017-06-28 13:08 UTC, AlbaMontis commented on app/src/containers/About/About.js
> +import { Grid, Row, Col, PageHeader, Image } from 'react-bootstrap';
Do you use Image in this file?

2017-06-28 13:12 UTC, shyyka submitted a review, later dismissed

2017-06-28 14:14 UTC, shyyka submitted a review, later dismissed

2017-06-28 14:48 UTC, shyyka submitted a review, later dismissed

2017-06-28 14:48 UTC, shyyka commented on .gitignore
> +package-lock.json
add blank line

2017-06-28 14:58 UTC, AlbaMontis submitted a review, later dismissed

2017-06-28 14:59 UTC, denisbodnar submitted a review, later dismissed

2017-06-28 18:02 UTC, 4asof4ik approved these changes

2017-06-28 18:47 UTC, denisbodnar approved these changes

2017-06-28 19:19 UTC, AlbaMontis approved these changes

2017-06-28 19:21 UTC, merged