Lvnod 121 update profile layout task
Lv-237-NodeJS/da-mi pull request #34
Opened 2017-06-25 21:55 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-120)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-121)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @denisbodnar
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of change

- created form to display user profile data
- added custom date picker for birthdate field

- p.s. Update profile logic will be implemented in the next task

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-26 08:00 UTC, denisbodnar submitted a review, later dismissed

2017-06-26 12:19 UTC, 4asof4ik requested changes
Why you create 2 PR with this code. Check other your profile PR

2017-06-26 12:19 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +                  <Col sm={5}>
ask guys about form fields

2017-06-26 12:44 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-01 18:44 UTC, 4asof4ik requested changes

2017-07-01 18:44 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +import 'react-datepicker/src/stylesheets/datepicker.scss';
Try import into common style and common import into profile styles

2017-07-05 09:23 UTC, closed without merging