LVNOD-80-Saving guests action
Lv-237-NodeJS/da-mi pull request #43
Opened 2017-06-29 15:21 UTC by AlbaMontis

…ails due to backend changes

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-80)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-88)

## Code reviewers

- [x] @yarvanya
- [x] @denisbodnar
- [x] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-29 15:58 UTC, yarvanya submitted a review, later dismissed

2017-06-29 16:34 UTC, denisbodnar submitted a review, later dismissed

2017-06-29 19:51 UTC, avoytovich submitted a review, later dismissed

2017-06-30 07:37 UTC, 4asof4ik requested changes

2017-06-30 07:37 UTC, 4asof4ik commented on app/src/redux/invite.js
> +        let guests;
I see 48-49 more than 2 times

2017-06-30 14:20 UTC, yarvanya submitted a review, later dismissed

2017-06-30 14:49 UTC, avoytovich submitted a review, later dismissed

2017-06-30 15:18 UTC, denisbodnar submitted a review, later dismissed

2017-07-01 18:39 UTC, 4asof4ik requested changes

2017-07-01 18:39 UTC, 4asof4ik commented on app/src/containers/Event/EventDetails.js
> +    this.props.guestActions.deleteGuest(id, guest.id);
Add guestActions into 36 line

2017-07-02 17:31 UTC, denisbodnar approved these changes

2017-07-02 19:11 UTC, avoytovich approved these changes

2017-07-03 10:16 UTC, yarvanya approved these changes

2017-07-03 10:38 UTC, 4asof4ik approved these changes

2017-07-03 11:30 UTC, merged