Lvnod 127 adjusting jest for testing react component and redux
Lv-237-NodeJS/da-mi pull request #47
Opened 2017-07-03 00:57 UTC by avoytovich

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @AlbaMontis
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  All reviewers agreed to merge the PR

2017-07-03 08:38 UTC, AlbaMontis commented on package.json
> +    "redux-thunk": "^2.2.0",
Look at "dependencies".

2017-07-03 08:38 UTC, AlbaMontis commented on package.json
> +    "babel-preset-react": "^6.24.1",
Look at "dependencies".

2017-07-03 08:38 UTC, AlbaMontis commented on package.json
> +    "babel-preset-es2015": "^6.24.1",
Look at "dependencies".

2017-07-03 08:38 UTC, AlbaMontis commented on test/Login_async_action_creators.test.js
> +    nock(API.HOST + API.PORT)
Use API.URL.

2017-07-03 08:38 UTC, AlbaMontis commented on test/Login_async_action_creators.test.js
> +const middlewares = [thunk];
Do you need this if you have only one middleware?

2017-07-03 10:19 UTC, avoytovich commented on package.json
> +    "babel-preset-es2015": "^6.24.1",
i took it from jest guide for adjusting work. If you know another way, could you tell me?

2017-07-03 10:25 UTC, avoytovich commented on package.json
> +    "babel-preset-react": "^6.24.1",
if you want that i understand something you will have to explain more simply

2017-07-03 10:27 UTC, avoytovich commented on package.json
> +    "redux-thunk": "^2.2.0",
what do you mean?

2017-07-03 10:27 UTC, avoytovich commented on test/Login_async_action_creators.test.js
> +const middlewares = [thunk];
i know only this way...

2017-07-03 10:51 UTC, AlbaMontis commented on package.json
> +    "babel-preset-es2015": "^6.24.1",
We already have this package in "dependencies".

2017-07-03 10:51 UTC, AlbaMontis commented on package.json
> +    "babel-preset-react": "^6.24.1",
We already have this package in "dependencies".

2017-07-03 10:51 UTC, AlbaMontis commented on package.json
> +    "redux-thunk": "^2.2.0",
We already have this package in "dependencies".

2017-07-03 10:55 UTC, 4asof4ik requested changes

2017-07-03 10:55 UTC, 4asof4ik commented on test/Login_async_action_creators.test.js
> +
drop

2017-07-03 10:55 UTC, 4asof4ik commented on test/Login_component.test.js
> +
drop

2017-07-03 13:26 UTC, avoytovich commented on test/Login_async_action_creators.test.js
> +
what must i drop? Sorry, but i don't understand what do you mean...

2017-07-03 13:27 UTC, avoytovich commented on test/Login_component.test.js
> +
what do you mean? Could you explain me in some simply form...thank's...

2017-07-03 15:47 UTC, avoytovich commented on test/Login_async_action_creators.test.js
> +
Done

2017-07-03 15:47 UTC, avoytovich commented on package.json
> +    "babel-preset-es2015": "^6.24.1",
Done

2017-07-03 15:47 UTC, avoytovich commented on package.json
> +    "babel-preset-react": "^6.24.1",
Done

2017-07-03 15:47 UTC, avoytovich commented on package.json
> +    "redux-thunk": "^2.2.0",
Done

2017-07-03 15:48 UTC, avoytovich commented on test/Login_component.test.js
> +
Done

2017-07-03 19:17 UTC, yarvanya submitted a review, later dismissed

2017-07-03 19:48 UTC, shyyka submitted a review, later dismissed

2017-07-03 19:48 UTC, shyyka commented on test/__snapshots__/Login_component.test.js.snap
> +    <div
is the necessary to brake elements with one attribute?

2017-07-03 20:10 UTC, AlbaMontis commented on app/src/components/Login/Login.js
> +        <Form className='login-form' horizontal onSubmit={this.handleSubmit} state = {this.state}>
Useless space around "=".

2017-07-03 20:42 UTC, AlbaMontis submitted a review, later dismissed

2017-07-03 20:42 UTC, avoytovich commented on app/src/components/Login/Login.js
> +        <Form className='login-form' horizontal onSubmit={this.handleSubmit} state = {this.state}>
Done

2017-07-03 20:43 UTC, yarvanya submitted a review, later dismissed

2017-07-03 21:14 UTC, avoytovich commented on test/__snapshots__/Login_component.test.js.snap
> +    <div
maybe) this is a snapshots...its created auto...

2017-07-04 11:22 UTC, yarvanya submitted a review, later dismissed

2017-07-04 11:41 UTC, AlbaMontis submitted a review, later dismissed

2017-07-04 12:00 UTC, shyyka submitted a review, later dismissed

2017-07-06 06:17 UTC, 4asof4ik requested changes

2017-07-06 06:17 UTC, 4asof4ik commented on test/Login_component.test.js
> +    const form = tree.children.filter(child => child.type === 'form')[0];
add empty line

2017-07-06 06:17 UTC, 4asof4ik commented on test/Login_component.test.js
> +    expect(tree).toMatchSnapshot();
and here

2017-07-06 06:17 UTC, 4asof4ik commented on package.json
> +      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
you have all this type of file?

2017-07-06 07:39 UTC, avoytovich commented on test/Login_component.test.js
> +    const form = tree.children.filter(child => child.type === 'form')[0];
Done

2017-07-06 07:39 UTC, avoytovich commented on test/Login_component.test.js
> +    expect(tree).toMatchSnapshot();
Done

2017-07-06 07:41 UTC, avoytovich commented on package.json
> +      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
Done...reduced some

2017-07-06 07:58 UTC, yarvanya submitted a review, later dismissed

2017-07-06 08:55 UTC, AlbaMontis submitted a review, later dismissed

2017-07-06 11:03 UTC, shyyka submitted a review, later dismissed

2017-07-07 09:47 UTC, yarvanya submitted a review, later dismissed

2017-07-07 11:10 UTC, AlbaMontis submitted a review, later dismissed

2017-07-07 11:34 UTC, shyyka submitted a review, later dismissed

2017-07-07 14:55 UTC, yarvanya submitted a review, later dismissed

2017-07-07 15:43 UTC, shyyka submitted a review, later dismissed

2017-07-07 20:19 UTC, AlbaMontis submitted a review, later dismissed

2017-07-08 14:13 UTC, 4asof4ik requested changes

2017-07-08 14:13 UTC, 4asof4ik commented on test/Login_reducers.test.js
> +describe('loginReduser execution', () => {
describe(this is not test)(after first describe no need empty line)
    describe (this is not test)
        it (this is test)
          (empty line after each test)
       it
  (empty line after each describe)
    describe
       it

       it


fix in this format

2017-07-08 15:15 UTC, avoytovich commented on test/Login_reducers.test.js
> +describe('loginReduser execution', () => {
done

2017-07-08 16:21 UTC, 4asof4ik requested changes

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_async_action_creators.test.js
> +  it('creates LOGIN_USER_SUCCESS when user has been logged in', () => {
додай пустий рядок перед it

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_async_action_creators.test.js
> +    expect(store.getActions()).toEqual(expectedActions);
додай пустий рядок перед  expect

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_component.test.js
> +    expect(tree).toMatchSnapshot();
додай пустий рядок перед expect

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_component.test.js
> +    expect(tree).toMatchSnapshot();
додай пустий рядок перед expect

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_reducers.test.js
> +      expect(loginReduser(state, action))
додай пустий рядок перед expect

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_reducers.test.js
> +      expect(loginReduser(state, action)).toEqual({
додай пустий рядок перед expect

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_reducers.test.js
> +      expect(loginReduser(state, loginActions.logout())).toEqual({
додай пустий рядок перед expect

2017-07-08 16:21 UTC, 4asof4ik commented on test/Login_reducers.test.js
> +      expect(loginReduser(state, action)).toEqual({
додай пустий рядок перед expect

2017-07-08 20:42 UTC, shyyka approved these changes

2017-07-08 23:04 UTC, 4asof4ik approved these changes

2017-07-09 07:17 UTC, merged