Lvnod 85 adding guests
Lv-237-NodeJS/da-mi pull request #48
Opened 2017-07-03 15:22 UTC by AlbaMontis

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-80)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-85)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @denisbodnar
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-07-03 15:33 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-03 18:21 UTC, denisbodnar submitted a review, later dismissed

2017-07-03 22:02 UTC, 4asof4ik requested changes

2017-07-03 22:02 UTC, 4asof4ik commented on app/src/components/GuestsModalForm/GuestsModalForm.js
> +  add = () => {
what add?

2017-07-03 22:02 UTC, 4asof4ik commented on app/src/components/GuestsModalForm/GuestsModalForm.js
> +    const newEmails = this.state.inputs.map((email, j) => (
j ??

2017-07-03 22:02 UTC, 4asof4ik commented on app/src/components/GuestsModalForm/GuestsModalForm.js
> +      inputs: this.state.inputs.filter((input, j) => index !== j)
j

2017-07-04 20:33 UTC, yurii-kokhalevych approved these changes

2017-07-04 21:29 UTC, yuliannakorol approved these changes

2017-07-04 21:40 UTC, denisbodnar approved these changes

2017-07-05 07:07 UTC, 4asof4ik approved these changes

2017-07-05 07:18 UTC, merged