Lvnod 120 - Update profile page view
Lv-237-NodeJS/da-mi pull request #49
Opened 2017-07-04 22:39 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-120)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-121)

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of change

- created Profile component which represents a form for displaying and updating profile info and avatar
- added updateProfile actions and reducers

![profileq jpeg](https://user-images.githubusercontent.com/23255707/27843909-991e9564-6122-11e7-9990-874b7fa12923.png)

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-07-04 22:49 UTC, yurii-kokhalevych commented on app/src/containers/Profile/Profile.js
> +  handleSubmit = (e) => {
delete ()

2017-07-05 05:56 UTC, yarvanya commented on app/src/containers/Profile/Profile.js
> +let FieldGroup = ({id, label, ...props}) => (
Here use "const".

2017-07-05 05:56 UTC, yarvanya commented on app/src/containers/Profile/Profile.js
> +
Delete empty space.

2017-07-05 05:56 UTC, yarvanya commented on app/src/containers/Profile/Profile.js
> +
Delete one empty space.

2017-07-05 07:47 UTC, AlbaMontis commented on app/src/containers/Profile/Profile.js
> +                    <span> </span>
Use css for this.

2017-07-05 07:55 UTC, AlbaMontis commented on app/src/containers/Profile/Profile.js
> +      first_name: this.props.profile.first_name,
Maybe just `this.state = this.props.profile` ?

2017-07-05 07:55 UTC, AlbaMontis commented on app/src/redux/profileReducers.js
> +      .put(API.HOST + API.PORT + '/api/profile/' + profileId)
Use API.URL.

2017-07-05 11:04 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-05 11:14 UTC, yarvanya submitted a review, later dismissed

2017-07-05 11:48 UTC, avoytovich submitted a review, later dismissed

2017-07-05 13:27 UTC, yarvanya submitted a review, later dismissed

2017-07-05 14:47 UTC, yarvanya submitted a review, later dismissed

2017-07-05 14:47 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-05 14:48 UTC, avoytovich submitted a review, later dismissed

2017-07-06 06:31 UTC, 4asof4ik requested changes

2017-07-06 06:31 UTC, 4asof4ik commented on app/src/redux/profileReducers.js
> +      .get(API.URL + '/api/user/' + userId)
use `${} ...... ${userId}`

2017-07-06 06:31 UTC, 4asof4ik commented on app/src/redux/profileReducers.js
> +      .put(API.URL + '/api/profile/' + profileId)
and here

2017-07-06 06:31 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +  componentWillReceiveProps(nextProps){
space before {

2017-07-06 06:31 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +  }
;

fix linter

2017-07-08 23:02 UTC, 4asof4ik requested changes

2017-07-08 23:02 UTC, 4asof4ik commented on app/src/containers/Profile/Profile.js
> +    const {profile} = this.props;
you dont need this const here

2017-07-08 23:02 UTC, 4asof4ik commented on app/src/redux/profileReducers.js
> +        if (error) {
improve

2017-07-08 23:02 UTC, 4asof4ik commented on app/src/redux/profileReducers.js
> +      .put(API.URL + `/api/profile/${profileId}`)
use `${}` for all

2017-07-09 06:53 UTC, yarvanya commented on app/src/containers/Profile/Profile.js
> +                  <Col  md={4} className='text-center'>
Delete one space.

2017-07-09 06:53 UTC, yarvanya commented on app/src/containers/Profile/Profile.js
> +                      <Image id='img-circle-avatar' src={profile.avatar} circle/>
Space before  />

2017-07-09 06:53 UTC, yarvanya commented on app/src/containers/Profile/Profile.js
> +
Delete this empty blank.

2017-07-09 07:27 UTC, 4asof4ik requested changes

2017-07-09 07:27 UTC, 4asof4ik commented on app/src/redux/eventsReducers.js
> +import  { API }  from './../helper/constants';
Api request from ./helper

2017-07-09 08:03 UTC, yuliannakorol commented on app/src/redux/eventsReducers.js
> +import  { API }  from './../helper/constants';
it won't work because /helper/index.js is not yet merged on dev

2017-07-09 10:40 UTC, yarvanya submitted a review, later dismissed

2017-07-09 18:57 UTC, yarvanya submitted a review, later dismissed

2017-07-09 19:22 UTC, avoytovich submitted a review, later dismissed

2017-07-09 19:42 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-09 19:52 UTC, lhalam commented
Conflicting files
app/src/redux/eventsReducers.js
app/src/redux/login.js

2017-07-09 20:00 UTC, avoytovich approved these changes

2017-07-09 21:06 UTC, yurii-kokhalevych approved these changes

2017-07-09 21:52 UTC, 4asof4ik approved these changes

2017-07-09 21:53 UTC, merged