LVNOD-83-gift-logic
Lv-237-NodeJS/da-mi pull request #51
Opened 2017-07-07 00:17 UTC by denisbodnar

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-83)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-97)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-98)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-100)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-101)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-102)

## Code reviewers

- [ ] @yarvanya
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-07-09 00:43 UTC, shyyka submitted a review, later dismissed

2017-07-09 07:30 UTC, yarvanya commented on app/src/containers/AddGift/AddGift.js
> +} from 'react-bootstrap';
Delete unneeded comma.

2017-07-09 07:30 UTC, yarvanya commented on app/src/containers/AddGift/AddGift.js
> +  constructor (props) {
Delete space before (

2017-07-09 07:30 UTC, yarvanya commented on app/src/containers/AddGift/AddGift.js
> +  render () {
Delete space before (

2017-07-09 07:30 UTC, yarvanya commented on app/src/containers/EditGift/EditGift.js
> +import { Modal, Button, FormGroup, FormControl, ControlLabel,
Delete unneeded comma.

2017-07-09 07:30 UTC, yarvanya commented on app/src/containers/EditGift/EditGift.js
> +  render () {
Delete space before (

2017-07-09 07:30 UTC, yarvanya commented on app/src/containers/EditGift/EditGift.js
> +
Delete this empty blank.

2017-07-09 07:30 UTC, yarvanya commented on app/src/redux/gift.js
> +const FETCH_GIFTS_SUCCESS = 'FETCH_GIFTS_SUCCESS';
First should be importing and after that declareting constants.

2017-07-09 07:30 UTC, yarvanya commented on app/src/redux/gift.js
> +      .get(API.URL + `/api/events/${eventId}/gifts`)
`${API.URL}/api/events/${eventId}/gifts`

2017-07-09 07:30 UTC, yarvanya commented on app/src/redux/gift.js
> +      .post(API.URL + `/api/events/${eventId}/gifts`)
The same.

2017-07-09 07:30 UTC, yarvanya commented on app/src/redux/gift.js
> +      .put(API.URL + `/api/event/${eventId}/gift/${giftId}`)
The same.

2017-07-09 07:30 UTC, yarvanya commented on app/src/redux/gift.js
> +      .delete(API.URL + `/api/event/${eventId}/gift/${giftId}`)
The same.

2017-07-09 18:28 UTC, 4asof4ik requested changes

2017-07-09 18:28 UTC, 4asof4ik commented on app/src/redux/gift.js
> +import request from './../helper/request';
fix path

2017-07-09 18:28 UTC, 4asof4ik commented on app/src/containers/Gift/Gift.js
> +import * as giftActions from '../../redux/gift';
path

2017-07-09 18:28 UTC, 4asof4ik commented on app/src/redux/gift.js
> +          dispatch({
improve check all

2017-07-09 19:33 UTC, yarvanya submitted a review, later dismissed

2017-07-09 19:43 UTC, yuliannakorol submitted a review, later dismissed

2017-07-09 19:43 UTC, shyyka submitted a review, later dismissed

2017-07-09 21:06 UTC, yuliannakorol submitted a review, later dismissed

2017-07-09 22:01 UTC, 4asof4ik requested changes

2017-07-09 22:01 UTC, 4asof4ik commented on app/src/containers/GiftList/GiftList.js
> +          <p>Description:&nbsp;{gift.description}</p>
&nbsp ? you have scss

2017-07-09 22:01 UTC, 4asof4ik commented on app/src/containers/GiftList/GiftList.js
> +          <p>Link:&nbsp;<a href={'http://' + gift.link}>{gift.link}</a></p>
`${}` and what if i need https

2017-07-10 00:34 UTC, shyyka submitted a review, later dismissed

2017-07-10 03:58 UTC, yarvanya submitted a review, later dismissed

2017-07-10 06:12 UTC, yuliannakorol submitted a review, later dismissed

2017-07-10 09:10 UTC, yarvanya submitted a review, later dismissed

2017-07-10 10:20 UTC, shyyka submitted a review, later dismissed

2017-07-10 15:13 UTC, yuliannakorol submitted a review, later dismissed

2017-07-10 18:25 UTC, yarvanya approved these changes

2017-07-10 19:06 UTC, yuliannakorol approved these changes

2017-07-10 21:32 UTC, shyyka approved these changes

2017-07-10 21:42 UTC, 4asof4ik approved these changes

2017-07-10 21:44 UTC, merged