Lvnod-119_Create comment component
Lv-237-NodeJS/da-mi pull request #53
Opened 2017-07-08 19:59 UTC by shyyka

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @denisbodnar
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-07-08 22:44 UTC, 4asof4ik requested changes

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentForm.js
> +import getAuthor from './../../helper/getAuthor';
you import helper in 6 line

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentForm.js
> +
drop line

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentForm.js
> +  constructor(props){
space before {

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentForm.js
> +    this.props.actions.createComment(eventId, giftId, commentData);
30-32 add into 29 line

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentForm.js
> +  render(){
space {

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentForm.js
> +          <img className="avatar" src={ this.props.author.avatar } />
select one code style {} with space inside or not

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentItem.js
> +  constructor(props){
check this file

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentItem.js
> +                      author={ this.props.author }
write const {} = this.props

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/helper/getAuthor.js
> +  return firstName + ' ' + lastName;
use `${}`

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Event/EventDetails.js
> +              <Comments eventId={id} giftId={1} author={this.props.owner} />
gift id hardcode

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentItem.js
> +                { this.props.user }<p> { commentsDate } | </p>
separate

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentItem.js
> +                    <CommentForm
create const and use them

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/containers/Comments/CommentItem.js
> +            this.props.comment.children ? (
create function which will be return this

2017-07-08 22:44 UTC, 4asof4ik commented on app/src/redux/commentCreateReducers.js
> +import  { API }  from './../helper/constants';
one time helper import  chack all files

2017-07-09 07:07 UTC, yarvanya commented on app/src/containers/Comments/CommentItem.js
> +  render(){
Space before {

2017-07-09 07:07 UTC, yarvanya commented on app/src/containers/Comments/CommentItem.js
> +                      hideForm={ () => this.setState({ showForm: false }) }/> :
Space before  />

2017-07-09 07:07 UTC, yarvanya commented on app/src/containers/Comments/Comments.js
> +
Delete this empty blank.

2017-07-09 07:07 UTC, yarvanya commented on app/src/containers/Comments/Comments.scss
> +  border-top: 1px solid #ddedeb;
Add this color to the constants in common.scss .

2017-07-09 07:07 UTC, yarvanya commented on app/src/containers/Comments/Comments.scss
> +  background-color: #f3fffd;
And this.

2017-07-09 07:07 UTC, yarvanya commented on app/src/redux/commentDeleteReducers.js
> +const COMMENT_DELETED = 'COMMENT_DELETED';
First should be importing and after that declareting constants.

2017-07-09 07:07 UTC, yarvanya commented on app/src/redux/commentCreateReducers.js
> +const COMMENT_CREATED = 'COMMENT_CREATED';
First should be importing and after that declareting constants.

2017-07-09 07:07 UTC, yarvanya commented on app/src/redux/commentsFetchReducers.js
> +const RETRIEVE_COMMENTS = 'RETRIEVE_COMMENTS';
First should be importing and after that declareting constants.

2017-07-09 17:12 UTC, shyyka commented on app/src/redux/commentsFetchReducers.js
> +const RETRIEVE_COMMENTS = 'RETRIEVE_COMMENTS';
Ok

2017-07-09 17:12 UTC, shyyka commented on app/src/redux/commentCreateReducers.js
> +const COMMENT_CREATED = 'COMMENT_CREATED';
Done

2017-07-09 17:17 UTC, shyyka commented on app/src/containers/Event/EventDetails.js
> +              <Comments eventId={id} giftId={1} author={this.props.owner} />
Temporary Comments are attached to the test component so far which will be replaced by adding a working one

2017-07-09 17:31 UTC, shyyka commented on app/src/containers/Comments/CommentForm.js
> +import getAuthor from './../../helper/getAuthor';
Done

2017-07-09 17:33 UTC, shyyka commented on app/src/containers/Comments/CommentForm.js
> +    this.props.actions.createComment(eventId, giftId, commentData);
Done

2017-07-09 18:04 UTC, shyyka commented on app/src/containers/Comments/Comments.js
> +
We talked on Friday that we left the blank line between render & return

2017-07-09 18:07 UTC, shyyka commented on app/src/containers/Comments/CommentForm.js
> +
Done

2017-07-09 18:08 UTC, shyyka commented on app/src/containers/Comments/CommentForm.js
> +          <img className="avatar" src={ this.props.author.avatar } />
Ok

2017-07-09 18:08 UTC, shyyka commented on app/src/containers/Comments/CommentItem.js
> +  constructor(props){
Done

2017-07-09 18:09 UTC, shyyka commented on app/src/containers/Comments/CommentItem.js
> +                    <CommentForm
Done

2017-07-09 22:11 UTC, 4asof4ik requested changes

2017-07-09 22:11 UTC, 4asof4ik commented on app/src/redux/commentDeleteReducers.js
> +      .delete(API.URL + `/api/event/${eventId}/gift/${giftId}/comment/${comment_id}`)
use for all (include api.url)

2017-07-09 22:11 UTC, 4asof4ik commented on app/src/redux/commentDeleteReducers.js
> +        if (err) {
improve check all reducers

2017-07-10 04:01 UTC, yarvanya submitted a review, later dismissed

2017-07-10 06:16 UTC, yuliannakorol submitted a review, later dismissed

2017-07-10 08:47 UTC, yuliannakorol submitted a review, later dismissed

2017-07-10 09:07 UTC, yarvanya submitted a review, later dismissed

2017-07-10 11:11 UTC, denisbodnar submitted a review, later dismissed

2017-07-10 12:18 UTC, shyyka commented on app/src/redux/commentDeleteReducers.js
> +        if (err) {
Done

2017-07-10 12:18 UTC, shyyka commented on app/src/redux/commentDeleteReducers.js
> +      .delete(API.URL + `/api/event/${eventId}/gift/${giftId}/comment/${comment_id}`)
Done

2017-07-10 15:13 UTC, denisbodnar submitted a review, later dismissed

2017-07-11 04:49 UTC, yarvanya submitted a review, later dismissed

2017-07-13 13:54 UTC, denisbodnar submitted a review, later dismissed

2017-07-13 13:54 UTC, denisbodnar commented on app/src/containers/Event/EventDetails.js
> +              <Gift id={id} author={this.props.owner} />
shorten this.props

2017-07-13 13:54 UTC, denisbodnar commented on app/src/containers/Gift/Gift.js
> +        <GiftList id={id} author={this.props.author} actions={actions} gifts={gifts}/>
same

2017-07-16 07:02 UTC, 4asof4ik requested changes

2017-07-16 07:02 UTC, 4asof4ik commented on app/src/redux/reducer.js
> +import commentsList from './commentsFetchReducers';
create one reducer and check how it should looks in Denys PR (action and reducer is separated )

2017-07-16 07:02 UTC, 4asof4ik commented on app/src/redux/commentsFetchReducers.js
> +        dispatch({
create const for action and use them here check all PR

2017-07-17 00:37 UTC, shyyka commented on app/src/redux/reducer.js
> +import commentsList from './commentsFetchReducers';
Done

2017-07-17 00:38 UTC, shyyka commented on app/src/redux/commentsFetchReducers.js
> +        dispatch({
Done

2017-07-17 15:09 UTC, denisbodnar submitted a review, later dismissed

2017-07-17 15:33 UTC, yarvanya submitted a review, later dismissed

2017-07-17 15:46 UTC, yuliannakorol submitted a review, later dismissed

2017-07-17 20:37 UTC, denisbodnar submitted a review, later dismissed

2017-07-17 21:03 UTC, yarvanya submitted a review, later dismissed

2017-07-18 14:40 UTC, yuliannakorol submitted a review, later dismissed

2017-07-23 14:27 UTC, denisbodnar approved these changes

2017-07-23 19:32 UTC, yarvanya approved these changes

2017-07-23 20:36 UTC, yuliannakorol approved these changes

2017-07-23 20:46 UTC, merged