LVNOD-157-Refactor-all-reducers
Lv-237-NodeJS/da-mi pull request #65
Opened 2017-07-15 22:15 UTC by denisbodnar

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-157)

## Code reviewers

- [ ] @yarvanya
- [ ] @AlbaMontis
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## CHECK LIST
- [ ]  СI passed
- [ ]  PR meets all conventions

2017-07-16 06:47 UTC, Vovk-Nazar requested changes

2017-07-16 06:47 UTC, Vovk-Nazar commented on app/src/components/EventsModalForm/editEventActions.js
> +  return {
=> ({
your object
})

check all PR

2017-07-16 06:47 UTC, Vovk-Nazar commented on app/src/containers/Event/eventActions.js
> +        dispatch({
create const with action and call this action here

check all action files

2017-07-16 06:47 UTC, Vovk-Nazar commented on app/src/containers/Event/inviteActions.js
>    return dispatch => {
fix this and check all action

2017-07-16 06:47 UTC, Vovk-Nazar commented on app/src/containers/Event/inviteActions.js
>      request()
fix 59 line

2017-07-16 18:31 UTC, shyyka submitted a review, later dismissed

2017-07-16 19:13 UTC, 4asof4ik requested changes

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Events/eventsListReducer.js
> +    ...state
Unnecessary  action

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Contacts/contactActions.js
> +
Unnecessary  action

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Contacts/contactActions.js
> +  dispatch(contactRequest());
And here

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/components/Login/loginActions.js
>      dispatch(loginUserRequest());
Unnecessary

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/components/Login/loginActions.js
> +  type: LOGIN_USER_REQUEST
Drop this action

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Profile/profileActions.js
> +  dispatch(updateProfileRequest());
Drop

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Profile/profileActions.js
> +  dispatch(retrieveProfileRequest());
Drop And action too

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Profile/profileActions.js
> +const updateProfileRequest = () => ({
Drop

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Profile/profileActions.js
> +const retrieveProfileRequest = () => ({
Drop

2017-07-16 19:13 UTC, 4asof4ik commented on app/src/containers/Events/eventsListActions.js
> +  dispatch(retrieveEventsRequest());
Drop And action

2017-07-17 05:52 UTC, yarvanya submitted a review, later dismissed

2017-07-17 07:28 UTC, shyyka submitted a review, later dismissed

2017-07-17 08:09 UTC, 4asof4ik approved these changes

2017-07-17 08:09 UTC, 4asof4ik commented on app/src/redux/configureStore.js
>    return createStore(
drop return

2017-07-17 09:10 UTC, yarvanya approved these changes

2017-07-17 09:11 UTC, merged