initial finished work with Routers
Lv-237-NodeJS/da-mi pull request #9
Opened 2017-05-25 10:48 UTC by avoytovich

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @denisbodnar
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-05-25 11:11 UTC, denisbodnar submitted a review, later dismissed

2017-05-25 11:11 UTC, denisbodnar commented on app/src/components/Address/Address.js
> +    		<Link to="/contacts/address/another_region">another_region</Link>
Use spaces, not tabs

2017-05-25 11:11 UTC, denisbodnar commented on app/src/components/Another_region/Another_region.js
> +}
Add line

2017-05-25 11:11 UTC, denisbodnar commented on app/src/components/index.js
> +export Another_region from './Another_region/Another_region';
Add a new line

2017-05-25 11:11 UTC, denisbodnar commented on app/src/router.js
> +import { Route, IndexRoute, Link } from 'react-router';
Imported Link but didn`t use

2017-05-25 11:11 UTC, denisbodnar commented on app/src/router.js
> +    		<Route path='/contacts/address/another_region' component={Another_region}/>
use spaces, not tabs

2017-05-25 12:07 UTC, AlbaMontis commented on app/src/components/Another_region/Another_region.js
> +export default class Another_region extends React.Component {
Use PascalCase for React components

2017-05-25 12:07 UTC, AlbaMontis commented on app/src/components/Address/Address.js
> +    	)
;

2017-05-25 12:14 UTC, avoytovich commented on app/src/components/Address/Address.js
> +    	)
JSX not a JS!!!

2017-05-25 12:36 UTC, denisbodnar submitted a review, later dismissed

2017-05-25 12:41 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-05-25 12:54 UTC, denisbodnar submitted a review, later dismissed

2017-05-25 12:55 UTC, yuliannakorol submitted a review, later dismissed

2017-05-25 13:01 UTC, AlbaMontis submitted a review, later dismissed

2017-05-25 13:01 UTC, AlbaMontis commented on app/src/components/Address/Address.js
> +    )
;

2017-05-25 19:23 UTC, 4asof4ik requested changes

2017-05-25 19:23 UTC, 4asof4ik commented on app/src/router.js
> +        <Route path='/contacts/address/another_region' component={AnotherRegion}/>
What is that path='/contacts/address/another_region'?

2017-05-25 19:23 UTC, 4asof4ik commented on app/src/components/Address/Address.js
> +        <Link to="/contacts/address/another_region">Another_region</Link>
??

2017-05-26 05:07 UTC, denisbodnar submitted a review, later dismissed

2017-05-26 05:12 UTC, AlbaMontis submitted a review, later dismissed

2017-05-26 06:13 UTC, yuliannakorol submitted a review, later dismissed

2017-05-26 20:56 UTC, 4asof4ik requested changes

2017-05-26 20:56 UTC, 4asof4ik commented on app/src/router.js
> +        <Route path='/contacts/address/another' component={AnotherRegion}/>
path should be with one name and then some params 
example: path = "/user/:id"

2017-05-27 11:57 UTC, denisbodnar submitted a review, later dismissed

2017-05-27 13:22 UTC, AlbaMontis submitted a review, later dismissed

2017-05-27 13:48 UTC, yuliannakorol submitted a review, later dismissed

2017-05-29 18:43 UTC, denisbodnar submitted a review, later dismissed

2017-05-29 18:43 UTC, denisbodnar commented on app/src/containers/index.js
> +export Maps from './Maps/Maps';
add line

2017-05-30 12:52 UTC, denisbodnar submitted a review, later dismissed

2017-05-30 12:58 UTC, yuliannakorol submitted a review, later dismissed

2017-05-30 13:09 UTC, AlbaMontis commented on app/src/components/index.js
> +export Maps from './Maps/Maps';
Add new line

2017-05-30 13:18 UTC, denisbodnar submitted a review, later dismissed

2017-05-31 07:12 UTC, 4asof4ik requested changes

2017-05-31 07:12 UTC, 4asof4ik commented on app/src/components/index.js
> +export About from './../contai/About/About';
'./../contai.........' what is that?

2017-05-31 07:12 UTC, 4asof4ik commented on app/src/containers/Address/Address.js
> +import { Link } from 'react-router';
import but not used

2017-05-31 10:27 UTC, AlbaMontis approved these changes

2017-05-31 11:29 UTC, yuliannakorol approved these changes

2017-05-31 14:18 UTC, denisbodnar approved these changes

2017-05-31 19:06 UTC, 4asof4ik approved these changes

2017-06-01 09:33 UTC, merged